### ISSUE TITLE
CTD before loading screen 

### ISSUE THREAD

**Issue by gregest** [StellarWind22/Fabric-Shield-Lib#141]
I installed a mod that uses FabricShieldLib and whenever I try to open the game it instantly crashes before even getting to the loading screen, looking at the latest.log it seems to mention fabricshieldlib a lot    

[latest.log](https://github.com/StellarWind22/Fabric-Shield-Lib/files/11018849/latest.log)

**Comment by CringeStar** [comment]
After looking at it, it seems our mixing into the LivingEntity damage method is mentioned. Could you please say what version mod you installed and possibly link it?

**Comment by gregest** [comment]
Ah sorry I forgot to mention that, it was the Fabric version FabricShieldLib-1.6.1-1.19.jar https://www.curseforge.com/minecraft/mc-mods/fabric-shield-lib/files/4153077   

though looking at it this seems to be an older version? I have no why curseforge downloads this older verison but even looking at versions there is only these 3 
![CurseForge_2023-03-21_23-25-19](https://user-images.githubusercontent.com/56032903/226755614-9c11979e-4d0f-4682-a753-2a013b680fc5.png)

**Comment by CringeStar** [comment]
1.6.1 is 3-4 versions behind our current lib. I think an issue like this was fixed between then and the current 1.7. This might be just the author of the pack not updating, so you can try to contact then to update to the newest lib version. I'm going to keep this open for a short while, but then close it ad it applies to an older version of the lib.

**Comment by gregest** [comment]
I am the author of the pack, but the issue is also that the newer versions are not downloadable through curseforge for some reason, is it possibly because the mod is not tagged as fabric and is only tagged as Java 17?

**Comment by CringeStar** [comment]
Ah I see, I checked curseforge, and lib version 1.7 for 1.19.2 was the only one not marked with fabric. See if you can download it through curseforge now.

**Comment by CringeStar** [comment]
You're welcome!
