### ISSUE TITLE
[1.19.2] Fabric Shield Crash

### ISSUE THREAD

**Issue by itsdinkd** [StellarWind22/Fabric-Shield-Lib#142]
occurred on my modpack, another quality modpack 2.

Updated to shield API 1.7 and crashed upon entering game

https://pastebin.com/JpakGKAx

**Comment by CringeStar** [comment]
It seems like the mod "MobZ" or something like that changes the `getCooldownTicks()` method, causing an error. Could you please link that mod and provide the version of it?

**Comment by CringeStar** [comment]
I looked at their code. seems this is the file causing the issue. https://github.com/rikka0w0/MobZReborn/blob/3835fe46b28b39d48ffbceaa6bf364863b9f42e2/fabric/src/main/java/net/mobz/mixin/MetalShieldMixin.java#L5

It overrides the `getCooldownTicks()` method:
```
@Mixin(Shield.class)
public abstract class MetalShieldMixin implements FabricShield {
	@Override
	public int getCooldownTicks() {
		return 100;
	}

	@Override
	public boolean supportsBanner() {
		return false;
	}
}
```

**Comment by Sunconure11** [comment]
https://bytebin.lucko.me/SBlm0liXxo

Encountered the same issue.

@StellarWind22 @rikka0w0

**Comment by Chris-Creates** [comment]
so whats the solution? do we bother mobz creator to fix it instead? sounds like a mobz issue then.

**Comment by CringeStar** [comment]
Seems so, and I have opened an issue on their Github, https://github.com/rikka0w0/MobZReborn/issues/35, but they haven't responded. @rikka0w0

**Comment by CringeStar** [comment]
fixed by other mod dev
