### ISSUE TITLE
Tag Issue - 1.7 - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [StellarWind22/Fabric-Shield-Lib#143]
`[Worker-Main-3/ERROR]: Couldn't load tag c:shields as it is missing following references: fabricshieldlib:fabric_shield (from Fabric Shield Lib), fabricshieldlib:fabric_banner_shield (from Fabric Shield Lib)
[Worker-Main-3/ERROR]: Couldn't load tag c:tools as it is missing following references: #c:shields (from Porting Lib Tags)
[Worker-Main-3/ERROR]: Couldn't load tag bookshelf:shields as it is missing following references: #c:shields (from Bookshelf)`

[latest.log](https://gist.github.com/SpigotDE/9af6fb0777811be2a27c41be09a2f4b0)

**Comment by LonelyBard** [comment]
I also have this error

**Comment by CringeStar** [comment]
Looking at the log, it seems this error is happening with many other tags. Does this occur when the mod is loaded by itself?

**Comment by SpigotDE** [comment]
Only happens with new version

The other tags in this log is a fabric seasons / chipped problem

I will try this standalone

**Comment by SpigotDE** [comment]
Its not happening when standalone (Shield lib + Fabric API)
only happens with some of the mods in our pack ... but idk which

**Comment by SpigotDE** [comment]
Never mind ... it happens even with Shield Lib & Fabric API
I forgot to load in a world ^^

[latest.log](https://gist.github.com/SpigotDE/58283e357afdce7decb4dbf2082a9a6b)

**Comment by Globox1997** [comment]
This is a simple issue with [https://github.com/StellarWind22/Fabric-Shield-Lib/blob/1.19.2/src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java#L86](https://github.com/StellarWind22/Fabric-Shield-Lib/blob/1.19.2/src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java#L86).
These two default items which fabric shield lib initializes only in development environment are in the c:shields tag.
Since they exist only in dev env, in prod env the tag will cry for having non existing items in it.

**Comment by CringeStar** [comment]
> This is a simple issue with https://github.com/StellarWind22/Fabric-Shield-Lib/blob/1.19.2/src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java#L86. These two default items which fabric shield lib initializes only in development environment are in the c:shields tag. Since they exist only in dev env, in prod env the tag will cry for having non existing items in it.

Yeah, that's what I initially suspected. The test items are in the tag for testing purposes, but I guess we could remove them to fix this.

**Comment by SpigotDE** [comment]
Will this get fixed in the next update?

**Comment by CringeStar** [comment]
Yes, this should be fixed in the next version.

**Comment by xR4YM0ND** [comment]
any updates on this?

**Comment by CringeStar** [comment]
I've wanted to push out a fix for this with the next update, but I want to resolve #142 along sith this, but there's a bit of a hold on that issue.

**Comment by CringeStar** [comment]
Fixed in 1.7.1, releasing tomorrow
