### ISSUE TITLE
v1.7 for 1.18.2 requires a version of midnightlib that no longer exists in searched locations.

### ISSUE THREAD

**Issue by Lord-drageon** [StellarWind22/Fabric-Shield-Lib#146]
trying to add a dependency to this mod so I can use it, I'm repeatedly running into the same issue when I attempt to run the client; 
"> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find maven.modrinth:midnightlib:0.4.3."
it seems that there is no site that is locatable that has midnightlib 0.4.3 in it, and I can't access this library's' gradle.properties to change it to something that would work.

Is there a way to get this version of the 1.18.2 version of the mod to use a different, actually existent version of midnightlib? I apologize if this isn't a very hard-to-solve error for other people, I've only just begun mod creation.

**Comment by CringeStar** [comment]
Will change to lib version 0.4.4 when I update 1.18.2 soon

**Comment by CringeStar** [comment]
Fixed in 1.7.1, releasing tomorrow
