### ISSUE TITLE
1.18.2 not building

### ISSUE THREAD

**Issue by Melanos0** [StellarWind22/Fabric-Shield-Lib#149]
the version for 1.18.2 isn't building, it says Could not find com.github.CrimsonDawn45:Fabric-Shield-Lib:v1.7-1.18.2 if i use v1.7-1.18.2
and it says Could not find maven.modrinth:midnightlib:1.1.0-fabric if i use 1.7-1.19.3

**Comment by CringeStar** [comment]
Fixed in 1.7.1, releasing tomorrow
