### ISSUE TITLE
Update to 1.20.2

### ISSUE THREAD

**Issue by xR4YM0ND** [StellarWind22/Fabric-Shield-Lib#151]
Could you update this lib pls.

Some mods depend on it and we can`t update our modpack.

**Comment by rikka0w0** [comment]
> Could you update this lib pls.
> 
> Some mods depend on it and we can`t update our modpack.

Haven't heard about any updates, two of my mods depend on this, and I cannot start porting to 1.20.1

**Comment by CringeStar** [comment]
> Could you update this lib pls.
> 
> Some mods depend on it and we can`t update our modpack.

sorry for the long wait, should be out in 1-3 days
