### ISSUE TITLE
World Creation Crash

### ISSUE THREAD

**Issue by NashornAufCrack** [StellarWind22/Fabric-Shield-Lib#171]
I have made a modpack and whenever I want to create a world minecraft crashes and gives me this crashreport

[crash-2023-12-05_12.48.18-client.txt](https://github.com/StellarWind22/Fabric-Shield-Lib/files/13559863/crash-2023-12-05_12.48.18-client.txt)

**Comment by DroidZed** [comment]
This is already a duplicate of #170
