### ISSUE TITLE
Crash upon blocking Blaze fireball

### ISSUE THREAD

**Issue by evilmoondragon** [StellarWind22/Fabric-Shield-Lib#174]
[Crash log here.](https://github.com/StellarWind22/Fabric-Shield-Lib/files/13796810/crash-2023-12-29_19.43.35-server.txt)

I added Reflection to my shield and things were going great.
But now when I block a Blaze's fireball, the game freezes for a few seconds and then crashes with a code -1.
I am unsure if this affects anything else or if it's a mod incompatibility, though it's a little inconvenient.

**Comment by evilmoondragon** [comment]
Update: It also applies to creeper explosions, and strangely enough, being set on fire by lava.

What seems to be happening is that the ticking causes Neruina to kick me/the entity out, causing the null pointer exception because now there is no attacker. And _then_ it crashes. I guess for now I'm going to disenchant my shield so that I don't crash.

**Comment by CringeStar** [comment]
hmm this is an interesting issue. What you described seems to be the problem. I'm going to test this on my end. Could you say what MC version you are on? Also, is the Reflection enchantment the one that is made inside our library or a custom one you made? Additionally, did this happen in the normal launcher or a dev environment?

**Comment by CringeStar** [comment]
Is this still an issue?

**Comment by CringeStar** [comment]
Hello?

**Comment by CringeStar** [comment]
If there is no response soon, I'll close this issue.
