### ISSUE TITLE
Custom banner shield uses FabricShieldLib shield texture when blocking

### ISSUE THREAD

**Issue by Partonetrain** [StellarWind22/Fabric-Shield-Lib#176]
https://github.com/StellarWind22/Fabric-Shield-Lib/assets/19861808/75f9f5e7-306a-439a-ac0d-d8ce6e1dd7b2

The tutorial (https://fabricmc.net/wiki/tutorial:shield) has the blocking model parent from fabric_banner_shield_blocking and doesn't specify the texture.
![image](https://github.com/StellarWind22/Fabric-Shield-Lib/assets/19861808/58d6adec-93b2-46de-8125-81128b1930de)

However, specifying the texture like so in the blocking model ([my JSON](https://github.com/Partonetrain/botaniacombat/blob/main/src/main/resources/assets/botaniacombat/models/item/elementium_banner_shield_blocking.json)) results in the shield using the default Minecraft missing texture.
```
  "textures":{
    "shield":"botaniacombat:entity/elementium_banner_shield"
  }
```
![image](https://github.com/StellarWind22/Fabric-Shield-Lib/assets/19861808/83029cf4-6402-43cd-87eb-2d789401edb0)

**Comment by CringeStar** [comment]
Thanks for catching this! It seems I changed it in the code but not in the wiki, will fix in a sec!

**Comment by CringeStar** [comment]
fixed

**Comment by Partonetrain** [comment]
Thanks for the quick response, but there still seems to be an issue.
using
 ``
  "textures":{
    "shield":"examplemod:item/netherite_shield"
  }
  ``
(which is what the wiki has now) in the blocking model use the non-banner shield. It looks like the banner disappears when blocking.

**Comment by CringeStar** [comment]
thats not what happens on my end, could you please show your model json files and your textures?

**Comment by Partonetrain** [comment]
D'oh, I had it parented to  `fabricshieldlib:item/fabric_shield_blocking` instead of `fabricshieldlib:item/fabric_banner_shield_blocking`, which is why it didn't work. My apologies, and thanks for your patience, haha.

**Comment by CringeStar** [comment]
It's all good! Happy you got it sorted out.
