### ISSUE TITLE
Version 1.7.2-1.19.4 on Modrinth is specified as compatible with MC version 1.19.2

### ISSUE THREAD

**Issue by silenium-dev** [StellarWind22/Fabric-Shield-Lib#178]
The version is specified as compatible with MC 1.19.2-1.19.4, but crashes with Minecraft 1.19.2.
There is also a version 1.7.2-1.19.2, so I believe it's just invalid metadata.

**Comment by CringeStar** [comment]
Oops! Didnt know I tocked that box, I marked that wrong then. The 1.19.4  version is for 1.19.3-1.19.4, while the 1.19.2 version is for 1.19-1.19.2. Will fix in a sec

**Comment by CringeStar** [comment]
Fixed
